# Site
name: ""
title: "Apprendre à coder"
description: "Développe tes compétences en assistant à nos workshops d'introduction au développement web"
meta_description: "Développe tes compétences en assistant à nos workshops d'introduction au développement web"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 8
baseurl: ''
email: 'Andry1287@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  Andry:
    name: Andry Rajohnson
    display_name: Andry
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: andry1287@gmail.com
    web: https://rajohnson-andry.tk
    twitter: https://twitter.com/RajohnsonAndry
    description: "Développeur Fullstack"

  Clara:
   name: Clara Morgen
   display_name: Clara
   gravatar: b1cc14991db7a456fcd761680bbc8f81
   email: wowthemesnet@gmail.com
   web: https://www.wowthemes.net/category/jekyll-themes/
   twitter: https://twitter.com/wowthemesnet
   description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
