# Site
name: "Codeasy"
title: "Apprendre à coder"
description: "Développe tes compétences en assistant à nos workshops d'introduction au développement web"
meta_description: "Développe tes compétences en assistant à nos workshops d'introduction au développement web"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 8
baseurl: ''
url: 'https://codedot.tk/'
email: 'Andry1287@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'jekyll-blog'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  Andry:
    name: Andry Rajohnson
    display_name: Andry
    gravatar: f3fe61732d08b94c1fa33ec1398a16fb
    email: andry1287@gmail.com
    web: https://rajohnson-andry.tk
    twitter: https://twitter.com/RajohnsonAndry
    description: "Développeur Fullstack"

  Clara:
   name: Clara Morgen
   display_name: Clara
   gravatar:
   email:
   web: https://www.claramorgeneyer.com/
   twitter: https://twitter.com/Clara_Morgen
   description: ""
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
